version: '3'
services:
  nginx:
    image: nginx
    restart: always
    command: nginx -g 'daemon off;'
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    depends_on:
      - app
      - mariadb

  app:
    build: .
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=noname
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=noname
      - MYSQL_PASSWORD=123456

volumes:
  db:
